on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --force --tags
      - run: brew install mingw-w64
      - working-directory: /tmp
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20230427/llvm-mingw-20230427-ucrt-macos-universal.tar.xz
          gunzip llvm-mingw-20230427-ucrt-macos-universal.tar.xz
          tar xf llvm-mingw-20230427-ucrt-macos-universal.tar
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.1'
          cache: true
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
